groups:
- name: Internal
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 2m
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes.'
    labels:
      severity: 'critical'

  - alert: rulesEvaluationDurationHigh
    expr: avg_over_time(prometheus_rule_group_last_duration_seconds{instance="prometheus:9090"}[5m]) > 1
    for: 0m
    annotations:
      title: 'Alerts rules evaluation duration too high'
      description: "Evaluation duration is {{ $value }}s"
    labels:
      severity: 'warning'

  - alert: PrometheusNotConnectedToAlertmanager
    expr: prometheus_notifications_alertmanagers_discovered < 1
    for: 0m
    labels:
      severity: critical
    annotations:
      description: "Prometheus cannot connect the alertmanager"